# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
defaults: &defaults
  working_directory: /go/src/github.com/packetloop/vault-gatekeeper
  docker:
    # specify the version
    - image: circleci/golang:1.12
      environment:
        GO111MODULE: "ON"

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: make dep
      - run: HOST=localhost PORT=443 TF_ACC= make test

  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  test-n-deploy:
    jobs:
      # a job must have a filters tags section to run as a part of a tag push and
      # all its transitively dependent jobs must also have a filters tags section.
      # ^ This is key, test must have tag filters since deploy requires it.
      - test:
          context: ops
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - deploy:
          context: ops
          requires:
            - test
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
